name: 'Repository Dispatcher'
description: 'Provide a description here'
author: 'Chili Piper'
inputs:
  config-file:
    description: 'Path to the config file'
    required: true
    default: 'dispatch.yml'
runs:
  using: 'node16'
  main: 'dist/index.js'
